### PR TITLE
Hypermedia responses

### PR DESCRIPTION
**Pull request by technoweenie**
This moves the mediaheader package into hypermedia.  Hypermedia is now broken up to separate the different ways of pulling hypermedia for an HTTP response.  The resource itself is only checked automatically if it's decoded through the response's media type.

This is written for #12 and should be applied first.

### CODE REVIEW

**Comment by technoweenie** [comment]
@jingweno: Would love your thoughts.  This lets us get away with skipping the `inject` library.  It also gives me a handy property to cache all of the hypermedia for a response in #12.  It shouldn't matter where the links come from.

**Comment by owenthereal** [comment]
@technoweenie The refactoring looks good to me. But we prob. need to pay attention to [race condition on the lazily loaded fields](https://github.com/lostisland/go-sawyer/blob/70d76cb362b7121f014ab406150aeed950f596a6/hypermedia/hal.go#L17-L21), if we're not setting the fields ahead of time at the JSON serialization step.

**Comment by technoweenie** [comment]
Ah good point.  I might even take that out since that `Rels()` shouldn't ever really be used.

I also don't intend to support these resource objects used in a shared context.  They should be initialized on every request, or passed around in channels.

**Comment by owenthereal** [comment]
This got me thinking though why we're using two approaches to set the relations, [one with lazy load](https://github.com/lostisland/go-sawyer/blob/70d76cb362b7121f014ab406150aeed950f596a6/hypermedia/hal.go#L16-L22), [the other with reflection](https://github.com/lostisland/go-sawyer/blob/70d76cb362b7121f014ab406150aeed950f596a6/hypermedia/hyperfields.go#L16-L27). I would still call the latter approach a DI (dependency injection) one, even though we don't use an library.

**Comment by owenthereal** [comment]
In case my last comment doesn't much sense, we're supposed to use the `HyperFieldRelations` function to fill the relations as part of the JSON serialization step, right?

**Comment by owenthereal** [comment]
Sorry, serialization => deserialization

**Comment by technoweenie** [comment]
The "HyperField" relations are to support the GitHub API (due to our initial support of `*_url` properties).  We could probably grab HAL links through  reflection by looking for the Links field (or the _links json tag).

**Comment by owenthereal** [comment]
Ah, ok, I think I'm more clear now. Would you think it makes sense to set both `HyperFieldRelations` and the `HALResource` relation at the deserialization step?

``` go
// in Response.Decode

func (r *Response) Decode(resource interface{}) error {
  // decode with media type decoder

  // fill relations by using HyperFieldRelations and some code from HALResource
}
```

It'll remove the lazy fields loading and make setting the relations consistent at one place: after the JSON deserialization steps.

**Comment by technoweenie** [comment]
That's how it works: https://github.com/lostisland/go-sawyer/pull/13/files#diff-b01558cabf60ed66d8a2c08b2bfaba31R56

Response.fillRels() is called after decoding if there aren't any errors.

The Rels() function is no longer needed and can be removed.  The goal of this PR is to store the relations in the sawyer.Response, regardless if they come from the header, HAL, or reflected from the resource's fields.

**Comment by owenthereal** [comment]
:+1:

**Comment by technoweenie** [comment]
Okay, I removed `Rels()`.  [This test](https://github.com/lostisland/go-sawyer/blob/hypermedia-responses/request_test.go#L50-L66) highlights how this should all work

**Pull request merged**
