### PR TITLE
initial httpcache interface

### PR DESCRIPTION
**Pull request by technoweenie**
WIP of an http caching system.

### CODE REVIEW

**Comment by technoweenie** [comment]
@jingweno: I'm feeling pretty good about this now.  The cache is fully integrated into the sawyer request/response cycle.  It handles expiration and sends etag/last modified headers for you.  There is also a specific function for getting Rels for an object:

``` go
// get this path from hypermedia somewhere, ideally
req, err := client.NewRequest("/repos/foo/bar") // path to a repository
rels := client.Rels(req, &Repository{})
rels["pull_requests"]
```

If the repository has been cached, then this is much faster than re-reading the cached request and parsing everything again.  The relations get cached separately.  This is handy because resources tend to have expirations around an hour.  Relations should never expire as long as the Accept header doesn't change.  When the Accept header changes, the cacher will generate a different key and re-fetch those objects.

**Comment by owenthereal** [comment]
:+1: Awwwwwwsome! I'll integrate it with `go-octokit` and see how it works with `gh`

**Comment by technoweenie** [comment]
Hold up, I just realized I don't even look at the HTTP verb, lol.  So if you cache a GET request, the POST request will come back with the cached content.  I'll get that fixed up ASAP.

**Comment by owenthereal** [comment]
@technoweenie Alrighty. Ping me when it's ready. Can't wait to try it out :smile_cat:

**Comment by technoweenie** [comment]
@jingweno: I think this should work now.  I figured HEAD/OPTIONS request are pretty rare, so I'm not going to bother caching them.

**Comment by technoweenie** [comment]
This has been running in production for about 4 months now, so I'm pretty confident this doesn't break existing code.  Though I haven't bothered setting up HTTP caching yet.  Is GH using this yet?

**Comment by owenthereal** [comment]
@technoweenie `gh` doesn't use the latest head with caching support yet. It's locked to [an earlier version](https://github.com/jingweno/gh/blob/master/Godeps/Godeps.json#L59-L62). [So is the `gh` branch of `hub`](https://github.com/github/hub/blob/gh/Godeps/Godeps.json#L57-L60). Go ahead and merge it to master and I'll make sure those projects get updated later.

**Pull request merged**
